# Generated by Django 4.1.7 on 2023-02-16 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('authors', models.CharField(max_length=400)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('isbn', models.CharField(max_length=16)),
                ('isbn_13', models.CharField(max_length=16)),
                ('language_code', models.CharField(max_length=5)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('text_reviews_count', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_issue_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.books')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.member')),
            ],
        ),
    ]
