# Generated by Django 4.1.7 on 2023-02-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='books',
            name='publication_date',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
