# Generated by Django 4.1.7 on 2023-02-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_books_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='average_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookId',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='num_pages',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='books',
            name='ratings_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='text_reviews_count',
            field=models.CharField(max_length=100),
        ),
    ]
