# Generated by Django 4.1.7 on 2023-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_books_average_rating_alter_books_bookid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='bookId',
            new_name='bookID',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='isbn_13',
            new_name='isbn13',
        ),
        migrations.AddField(
            model_name='books',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
