# Generated by Django 4.1.7 on 2023-02-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_bookid_books_bookid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='num_pages',
        ),
    ]
