# Generated by Django 4.1.7 on 2023-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_books_num_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='num_pages',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
