# Generated by Django 4.1.7 on 2023-02-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_book',
            name='book_issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='return_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
