# Generated by Django 4.1.7 on 2023-02-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_issue_book_book_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_book',
            name='book_issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue_book',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
